### PR TITLE
fix: casestart object creation

### LINKED ISSUE #94: API return values of /casestart are lists
The newly created API endpoint /casestart on scenario instances returns lists of values instead of plain strings, as shown in Image 1.

- [ ] Correct return value
- [ ] Add endpoint documentation

Image 1

### PR DESCRIPTION
**Pull request by tommartensen**
Fixes how the casestart objects in the list of all casestarters for a scenario are aggregated. 
Fixes #94

### CODE REVIEW

**Comment by tommartensen** [comment]
@friedow Can you check whether this is what you described in the issue?
@marhew Can you give me a pointer for the documentation of this endpoint?

**Comment by marhew** [comment]
@tommartensen This endpoint is not documented in swagger yet. What information would you need? We need to find out how to automatically generate the swagger.yaml file from the codebase.

**Comment by tommartensen** [comment]
I did not find an up-to-date documentation of the API. The `swagger.yaml` is five months old, the `docs` folder was not touched in two years. 
Is the swagger file the desired state of the API?

**Comment by marhew** [comment]
The intended behavior of the endpoint should be documented in the code, from which `swagger.yaml` should be generated (#100).
This endpoint should return a list of case start triggers, with the request key and event query for each.

**Comment by tommartensen** [comment]
You can test the behaviour with this case model: 
[5b241616e29c56002e120766.json.txt](https://github.com/bptlab/chimera/files/2107321/5b241616e29c56002e120766.json.txt)

**Pull request merged**
